project_id = "hnftxautmxviwrfuaosu"

[functions.mercado-pago]
verify_jwt = false

[functions.ia-musical]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false
